# Generated by Django 4.2.6 on 2024-10-10 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sjop', '0004_rating_text_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-product']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product'], name='sjop_rating_product_4bb32f_idx'),
        ),
    ]
