# Generated by Django 4.2.6 on 2024-10-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjop', '0005_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
