# Generated by Django 4.2.6 on 2024-10-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjop', '0009_marketshop_product_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMarketShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Категории магазинов',
                'verbose_name_plural': 'Категория магазина',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sjop_catego_name_10ffa5_idx')],
            },
        ),
        migrations.AddField(
            model_name='marketshop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_shop', to='sjop.categorymarketshop'),
        ),
    ]
