# Generated by Django 4.2.6 on 2024-10-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjop', '0010_categorymarketshop_marketshop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketshop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_shop', to='sjop.categorymarketshop'),
        ),
    ]
