# Generated by Django 4.2.6 on 2024-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupone',
        ),
    ]
