"""
Django settings for myshopss99 project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import LOGIN_REDIRECT_URL
from django.urls import reverse_lazy
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-inv*2y%a5v7b9kga47l=xq_+)m3urs&vw--ih%2@0*w$!+47hv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'account.apps.AccountConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sjop.apps.SjopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'coupens.apps.CoupensConfig',
    'easy_thumbnails',
    'widget_tweaks',
    'phonenumber_field',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshopss99.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sjop.context_processor.categories'
            ],
        },
    },
]

WSGI_APPLICATION = 'myshopss99.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'myshopss99/static'
]

STATIC_ROOT = 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

CART_SESSION_ID = 'cart'


LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'shop:product'

LOGOUT_REDIRECT_URL = 'logout'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'account.authentication.UserAuthenticetionEmail',
]



STRIPE_PUBLISHABLE_KEY = 'pk_test_51PYaFY065gR4p38Hwud6cCmMnL07yTJMxa4rOv7FSkbkv6yh49EbVRcF7z1nWnyX8cCb74TpbJPVdWVl1wUEDdgz009TvfcmY4'

STRIPE_SECRET_KEY = 'sk_test_51PYaFY065gR4p38HVxy2Y4k28xBnGi9G12nUxlCpK0fnLALs9cb5Q29Usyoirs3K20MYM8YCbkcSWrF9nlrIxyoY00gZ2Q3ICP'

STRIPE_API_VERSION = '2024-06-20'

STRIPE_WEBHOOK_SECRET = 'whsec_d2c3d613e246ccc1868acd4f04d25970830fd390bcea475d9cd1fac4dcfd90e0'


ABSOLUTE_URL_OVERRIDES = {
    'auth.user' : lambda u:reverse_lazy('user_detail',
                                        args=[u.username])
}

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_HOST_USER = 'kaznacheev6969@gmail.com'

EMAIL_HOST_PASSWORD = 'ltna lefv dxca pxdy'

EMAIL_PORT = 587

EMAIL_USE_TLS = True



CELERY_BEAT_SCHEDULE = {
    'delete-unpaid-orders-every-minutes': {
        'task': 'orders.tasks.delete_unpaid_orders',
        'schedule': crontab(minute='*/30'),  # Каждые 30 минут
    },
}