# Generated by Django 4.2.6 on 2024-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
